language: objective-c
xcode_project: TestProject.xcodeproj /Users/Haritha/Documents/R\&D/TestProject/TestProject
xcode_scheme: TestProject
script:
  - xctool -project TestProject.xcodeproj -scheme TestProject -sdk iphonesimulator
  - xctool test -project TestProject.xcodeproj -scheme TestProject -sdk iphonesimulator
